version: '3.8'

services:
  app:
    build: .
    container_name: product_cart_management_app
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${USER}:${PASSWORD}@postgres_db:${DB_PORT}/${DATABASE}?connect_timeout=10
  
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
