"""initial migration

Revision ID: 19cc7828841a
Revises: 
Create Date: 2025-01-27 18:09:09.811027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cc7828841a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_table2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cart_items', 'qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_cart_items_cart_item_id'), 'cart_items', ['cart_item_id'], unique=False)
    op.drop_constraint('cart_items_product_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_constraint('cart_items_cart_id_fkey', 'cart_items', type_='foreignkey')
    op.create_index(op.f('ix_carts_cart_id'), 'carts', ['cart_id'], unique=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('products', 'quantity_in_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.alter_column('sample_table', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('sample_table', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample_table', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample_table', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.alter_column('products', 'quantity_in_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_carts_cart_id'), table_name='carts')
    op.create_foreign_key('cart_items_cart_id_fkey', 'cart_items', 'carts', ['cart_id'], ['cart_id'], ondelete='CASCADE')
    op.create_foreign_key('cart_items_product_id_fkey', 'cart_items', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cart_items_cart_item_id'), table_name='cart_items')
    op.alter_column('cart_items', 'qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('sample_table2')
    # ### end Alembic commands ###
