"""correcting datetime columns

Revision ID: e81826d5cd5b
Revises: 38e078fda4ce
Create Date: 2025-01-30 00:26:56.632344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81826d5cd5b'
down_revision: Union[str, None] = '38e078fda4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['cart_id'])
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    # ### end Alembic commands ###
